---
- name: Update all packages
  hosts: all

  tasks:
    - name: Update all installed packages
      ansible.builtin.package:
        update_cache: true
        upgrade: true
        cache_valid_time: 3600
